### ISSUE TITLE
Should a new incognito window know I'm logged in?

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#102]
If I login to one chrome window at
https://development.arxiv.org/user/login
then I open a new incognito window and direct it to 
https://development.arxiv.org/user/login
It sometimes displays that I am logged in.

This is the screen that comes up from a new incognito window with 
![image](https://user-images.githubusercontent.com/11538356/58965878-47fefb80-877f-11e9-8e62-a6d8eb2313e2.png)

**Comment by erickpeirson** [comment]
Chrome is sending the auth cookie (for better or worse)...not our bug.
