### ISSUE TITLE
A TeX submission with PDF article included in source does not compile as TeX

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#106]
tested on classic submit/2288326 with the 2288326.pdf uploaded alongside the TeX source files

**Comment by erickpeirson** [comment]
This sounds like a connectivity issue between UI and filemanager.

- User uploads TeX source
- User then uploads PDF
- Proceeds, on processing step shows already completed

UI is not getting the updated checksum for filemanager, updating the submission.

**Comment by erickpeirson** [comment]
Related to https://github.com/arXiv/arxiv-submission-ui/issues/101

**Comment by erickpeirson** [comment]
Related to https://github.com/arXiv/arxiv-submission-ui/issues/107

**Comment by erickpeirson** [comment]
Going to close in favor of #101
