### ISSUE TITLE
Should the compilation_log link force a reload

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#110]
When I go through multiple reprocessing steps the compilation log didn't change. Then I realized it needed refreshing.

Is there a way to force a refresh on this page
https://development.arxiv.org/submit/2715274/compilation_log

Or on this page 
file_process 
Have the "View raw log" button trigger a reload as it links?

**Comment by erickpeirson** [comment]
Cross-ref as [ARXIVNG-2218]

[ARXIVNG-2218]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2218
