### ISSUE TITLE
Jump to process page after selecting edit submission from Manage Submissions page generates 500 error

### ISSUE THREAD

**Issue by DavidLFielding** [arXiv/arxiv-submission-ui#127]
Jumping to process page of existing submission generates 500 error.

![Screen Shot 2019-06-10 at 12 00 14 PM](https://user-images.githubusercontent.com/2325384/59208680-91808980-8b77-11e9-9bc0-7b02c9006585.png)

**Comment by erickpeirson** [comment]
Having a hard time reconstructing. I wonder if this is related to #113 . Once that is fixed, I'm curious to see if this goes away.
