### ISSUE TITLE
TeX isms in author metadata field show TeX source in preview

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#134]
If there are TeX accents in the author metadata field It looks like the Preview step does now show the accented characters and instead displays the TeX.

![image](https://user-images.githubusercontent.com/11538356/59366205-f1a63580-8d07-11e9-891a-23df700a3570.png)

**Comment by bdc34** [comment]
This issue probably affects the abs pages on production too.

**Comment by bdc34** [comment]
@jimentwood @mhl10  Do you want the authors displayed as html <a> tags with search links or just as strings?

**Comment by mhl10** [comment]
@bdc34 I think a safe bet is to just do what the browse macro is doing by default, which I think is with search links?
