### ISSUE TITLE
Add SASS middleware

### ISSUE THREAD

**Issue by bdc34** [arXiv/arxiv-submission-ui#139]
Currently we have some sass files but nothing to compile them.

Add middleware to compile sass as described here: https://sass.github.io/libsass-python/frameworks/flask.html#directory-layout

Also, compile on Flask app startup if is not development/debugging.

**Comment by bdc34** [comment]
Once setup, remove sass derivatives from source control.

**Comment by erickpeirson** [comment]
We're going to put this on hold until I'm back. Leaning strongly against any kind of compilation on the fly. So far our sass builds fine with sass. We can look at this in the context of build/deployment, but disinclined to add more runtime stuff unless there is a compelling reason.
