### ISSUE TITLE
Submission dashboard bleeds right on mobile

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-submission-ui#86]
Android 9 (Pixel 3 XL)

![Screenshot_20190604-200552](https://user-images.githubusercontent.com/3451594/58921423-a6d35f00-8704-11e9-87d4-752909f0413d.png)

**Comment by bdc34** [comment]
@mhl10  fixed this in PR https://github.com/arXiv/arxiv-submission-ui/pull/119 
as part of https://arxiv-org.atlassian.net/browse/ARXIVNG-2203
