### ISSUE TITLE
CSRF timeout is too short

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-submission-ui#87]
In the time I typed this out on mobile the CSRF token had expired. [ARXIVNG-2202]

![Screenshot_20190604-200454](https://user-images.githubusercontent.com/3451594/58921654-a4bdd000-8705-11e9-96a0-1152529f817b.png)

[ARXIVNG-2202]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2202

**Comment by bdc34** [comment]
This timeout seems to be here:
https://github.com/arXiv/arxiv-base/blob/master/arxiv/forms/csrf.py#L92
```
def _new_expiry() -> str:
        return (datetime.now() + timedelta(seconds=300)).isoformat()
```

**Comment by erickpeirson** [comment]
Jup. That shouldn't be hard-coded. Probably should:
- Make the timeout (number of seconds) a class attribute (e.g. ``SessionCSRF.TIMEOUT_SECONDS``)
- Increase the timeout to something more reasonable
- In the UI, if we need even longer timeouts we can subclass ``SessionCSRF`` with a different ``TIMEOUT_SECONDS`` and use it on ``CSRFForm`` children.
