### ISSUE TITLE
Cross list page bleeds right on mobile

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-submission-ui#89]
Looks like the form pushes past the viewport. Android 9 Pixel 3 XL. [ARXIVNG-2200]

![Screenshot_20190604-195604](https://user-images.githubusercontent.com/3451594/58921811-50672000-8706-11e9-9943-f2f5591d8959.png)

[ARXIVNG-2200]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2200

**Comment by mhl10** [comment]
Fixed in https://github.com/arXiv/arxiv-submission-ui/pull/119
