### ISSUE TITLE
Link in help text on /classification needs removal or work

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#94]
Empty link in help text for /classification:
If you are not sure, check the <a href="">category descriptions</a>. 

The issue is this page does not exist in a public location yet.

Either we could remove the link for now. Or we could work on this related ticket 
https://arxiv-org.atlassian.net/browse/ARXIVNG-1728

**Comment by erickpeirson** [comment]
For pre-alpha, remove link (and then remove label here). Leave this open until [ARXIVNG-1728] is resolved.

[ARXIVNG-1728]: https://arxiv-org.atlassian.net/browse/ARXIVNG-1728

**Comment by erickpeirson** [comment]
Cross-ref: [ARXIVNG-2216]

[ARXIVNG-2216]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2216
