### ISSUE TITLE
Add note about size exemptions on /file_upload blue box

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#96]
https://arxiv-org.atlassian.net/browse/ARXIVNG-2204

**Comment by erickpeirson** [comment]
> The current text does not include any mention of exemptions. We need to add some reference and links to that.

> Accepted file properties

> Names containing a-z A-Z 0-9 . , - _
Total compressed package size limit: 6MB
Total uncompressed package size limit: 18MB
Individual PDF size limit: 15MB

**Comment by erickpeirson** [comment]
Per @jimentwood:

> More information about [submission size, and exemptions to size limits](https://arxiv.org/help/sizes).
