### ISSUE TITLE
Fix help link at /confirmation

### ISSUE THREAD

**Issue by jimentwood** [arXiv/arxiv-submission-ui#99]
To view status or unsubmit your submission, use the links on the <a href="/">Manage Submissions</a> page.

I believe that should link to https://arxiv.org/user/ unless there is a new NG url for the user dashboard.

**Comment by jimentwood** [comment]
The link is in the help text and the button

**Comment by erickpeirson** [comment]
Cross-ref: [ARXIVNG-2215]

[ARXIVNG-2215]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2215

**Comment by bdc34** [comment]
@DavidLFielding, You have marked ARXIVNG-2215 as done. Can you assign this issue to yourself and close it too?
